language: cpp
sudo: required
before_install:
  - "sudo apt-get update -qq"
  - "sudo apt-get install -qq valgrind wget"
  - "wget http://users.ugent.be/~stevvdnb/gcc-6.0.0-no-futex-lib.tar.gz"
  - "tar -xzf gcc-6.0.0-no-futex-lib.tar.gz"
  - "ls; ls gcc-6.0.0-no-futex-lib"
install:
  - "g++ -o main main.cpp -fopenmp"
  - "g++ -o main_corrected main_corrected.cpp -fopenmp"
script:
  - "export OMP_NUM_THREADS=4; bash valgrind.sh;"
